config/routes.rb
Rails.application.routes.draw do
  root 'application#wellcome'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/listing_historys/:id/prod_desc', to: 'listings#prod_desc', via: 'get', :as => 'prod_desc'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :channels do
    member do
      get 'listings/new', to: 'listings#new'
    end
  end

  resources :listings do
    member do
      post '/historys', to: 'listings#new_history'
      get '/historys', to: 'listings#historys'
    end
  end
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  before_update :set_edit_times
  validates :name, presence: true, uniqueness: true
  has_many :listings

  def sort_name
    case self.name.downcase
      when 'amazon.com', 'amazon_us', 'us'
        'us'
      when 'amazon.co.uk', 'amazon_uk', 'uk'
        'uk'
      when 'amazon.fr', 'amazon_fr', 'fr'
        'fr'
      when 'amazon.es', 'amazon_es', 'es'
        'es'
      when 'amazon.de', 'amazon_de', 'de'
        'de'
      when 'amazon.it', 'amazon_it', 'it'
        'it'
      when 'amazon.co.jp', 'amazon_jp', 'jp'
        'jp'
      else
        raise RuntimeError('Error, invalid channel name!')
    end
  end

  private
  def set_edit_times
    self.edit_times = self.edit_times + 1
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @channels = Channel.all
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      flash[:success] = '创建成功.'
      redirect_to channels_url
    else
      render 'new'
    end
  end

  def show
    @channel = Channel.find(params[:id])
  end

  def destroy
    @channel = Channel.find(params[:id])
    if @channel.destroy
      flash[:success] = '删除成功.'
    else
      flash[:danger] = '删除失败.'
    end
    redirect_to channels_url
  end

  def edit
    @channel = Channel.find(params[:id])
    render 'new'
  end

  def update
    @channel = Channel.find(params[:id])
    if @channel.update(channel_params)
      flash.now[:success] = '修改成功.'
    else
      flash.now[:danger] = '修改失败.'
    end
    render 'new'
  end

  private
  def channel_params
    params.require(:channel).permit(:name)
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/index.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <%= link_to '添加新渠道', new_channel_url, class: 'btn btn-success' %>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <table class="table table-bordered table-hover table-condensed">
      <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Edit Times</td>
        <td>Action</td>
      </tr>
      <% @channels.each do |channel| %>
        <%= content_tag_for(:tr, channel) do %>
          <td><%= channel.id %></td>
          <td><%= link_to channel.name, channel %></td>
          <td><%= channel.edit_times %></td>
          <td>
            <%= link_to '更新', edit_channel_url(channel.id) %>
            <%= link_to '删除', channel, method: 'delete', data: { :confirm => 'Are you sure?' } %>
          </td>
        <% end %>
      <% end %>
    </table>
  </div>
</div>


app/views/channels/new.html.erb
<div class="row">
  <%= render 'shared/validate_errors', model: @channel %>

  <div class="col-md-6 col-md-offset-3">

    <%= form_for @channel do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <%= f.submit :class => 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/channels/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>Name: <%= @channel.name %></h2>
  </div>
</div><br/>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to '创建此渠道的 Listing', listings_new_channel_url(@channel), class: 'btn btn-primary' %>
    <%= link_to '返回列表', channels_url, class: 'btn btn-primary' %>
  </div>
</div>