config/routes.rb
Rails.application.routes.draw do
  root 'application#wellcome'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/listing_historys/:id/prod_desc', to: 'listings#prod_desc', via: 'get', :as => 'prod_desc'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :channels do
    member do
      get 'listings/new', to: 'listings#new'
    end
  end

  resources :listings do
    member do
      post '/historys', to: 'listings#new_history'
      get '/historys', to: 'listings#historys'
    end
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  validates :name, :asin, presence: true
  validates :channel_id, presence: true

  belongs_to :channel
  has_and_belongs_to_many :tags
  has_many :listing_histories

  def fetch_listing
    str = request_json
    parse_json_to_history(str)
  end

  def request_json
    http = Curl::Easy.new(base_url(self.channel.sort_name, asin)) do |c|
      c.encoding = 'gzip'
      c.headers['User-Agent'] = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.101 Safari/537.11'
      c.headers['Accept-Charset'] = 'utf-8'
      c.timeout = 20
    end
    http.perform
    response = http.body_str
    if is_normal_result?(response)
      return response
    else
      request_json
    end
  end

  def parse_json_to_history(json_str)
    listing_history = self.listing_histories.build
    json = JSON.parse(json_str)
    listing_history.title = json['title']
    listing_history.price = json['price'].to_f
    listing_history.seller_name = json['by_who']
    listing_history.main_img_url = json['main_image']
    listing_history.prod_desc = json['product_desc']
    listing_history.rating_score = json['review_rating']
    listing_history
  end

  def is_normal_result?(json)
    if json.nil? || json.include?('error')
      false
    else
      true
    end
  end

  def base_url(market, asin)
    "http://crawl.easya.cc/listing/#{market}/#{asin}.json"
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.all
  end

  def new
    @listing = build_listing
  end

  def create
    @listing = Listing.new(new_listing_params)
    if @listing.save
      flash[:success] = '添加 Listing 成功'
      redirect_to listings_url
    else
      render 'new'
    end
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(update_listing_params)
      flash.now[:success] = '修改成功.'
      redirect_to @listing
    else
      render 'edit'
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    if @listing.destroy
      flash[:success] = '删除成功.'
    else
      flash[:danger] = '删除失败.'
    end
    redirect_to listings_url
  end

  def new_history
    @listing = Listing.find(params[:id])
    @listing_history = @listing.fetch_listing
    respond_to do |format|
      if @listing_history.save
        format.js
      end
    end
  end

  def historys
    listing = Listing.find(params[:id])
    @listing_histories = listing.listing_histories.order('created_at DESC').page(params[:page])
  end

  def prod_desc
    @listing_history = ListingHistory.find(params[:id])
  end

  private

  def build_listing
    if params[:channel_id]
      channel = Channel.find(params[:channel_id])
      channel.listings.build
    else
      Listing.new
    end
  end

  def new_listing_params
    params.require(:listing).permit(:name, :asin, :channel_id)
  end

  def update_listing_params
    params.require(:listing).permit(:name, :asin, :channel_id, :tag_ids => [])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<div class="row">
  <%= render 'shared/validate_errors', model: @listing %>

  <div class="col-md-6 col-md-offset-3">

    <h1>Edit Listing</h1>
    <%= form_for @listing do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :asin %>
        <%= f.text_field :asin, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :channel_id %>
        <%= f.collection_select :channel_id, Channel.all, :id, :name, {}, {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= f.label :tags %>
        <%= f.collection_select :tag_ids, Tag.all, :id, :name, {:selected => @listing.tag_ids},
                                {:multiple => true, class: "form-control"} %>
      </div>

      <%= f.submit :class => 'btn btn-default' %>
      <%= link_to '返回列表', listings_url, class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/listings/historys.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <table class="table table-bordered table-hover table-condensed">
      <tr>
        <td>Title</td>
        <td>Price</td>
        <td>SellerName</td>
        <td>Img</td>
        <td>Product Desc</td>
        <td>Rating Score</td>
        <td>记录时间</td>
      </tr>
      <% @listing_histories.each do |history| %>
        <%= content_tag_for(:tr, history) do %>
          <td><%= history.title %></td>
          <td><%= history.price %></td>
          <td><%= history.seller_name %></td>
          <td><img src="<%= history.main_img_url %>" height="200" width="200"></td>
          <td>
            <%= link_to '点击查看', 'javascript:void(0);', data: {:url => prod_desc_url(history.id)} %>
          </td>
          <td><%= history.rating_score %></td>
          <td><%= history.created_at %></td>
        <% end %>
      <% end %>
    </table>
    <%= paginate @listing_histories %>
  </div>
</div>

app/views/listings/index.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <%= link_to '创建新 Listing', new_listing_url, class: 'btn btn-success' %>
  </div>
</div><br/>

<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <table class="table table-bordered table-hover table-condensed">
      <tr>
        <td>#ID</td>
        <td>Name</td>
        <td>ASIN</td>
        <td>Tags</td>
        <td colspan="4">Action</td>
      </tr>
      <% @listings.each do |listing| %>
        <%= content_tag_for(:tr, listing) do %>
          <td><%= listing.id %></td>
          <td><%= listing.name %></td>
          <td><%= listing.asin %></td>
          <td>
            <% listing.tags.each do |tag| %>
              <span class="label label-info"><%= tag.name %></span>
            <% end %>
          </td>
          <td>
            <%= link_to '抓取新历史', historys_listing_url(listing.id), method: 'post', remote: true, data: {'disable-with' => "正在抓取..."} %>
            <%= link_to '查看历史', historys_listing_url(listing.id) %>
          </td>
          <td>
            <%= link_to '查看', listing_url(listing.id) %>
          </td>
          <td>
            <%= link_to '更新', edit_listing_url(listing.id) %>
          </td>
          <td>
            <%= link_to '删除', listing, method: 'delete', data: {:confirm => 'Are you sure?'} %>
          </td>
        <% end %>
      <% end %>
    </table>
  </div>
</div>


app/views/listings/new.html.erb
<div class="row">
  <%= render 'shared/validate_errors', model: @listing %>

  <div class="col-md-6 col-md-offset-3">

    <h1>New Listing</h1>
    <%= form_for @listing do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :asin %>
          <%= f.text_field :asin, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.collection_select :channel_id, Channel.all, :id, :name, {}, {class: "form-control"} %>
        </div>
        <%= f.submit :class => 'btn btn-default' %>
        <%= link_to '返回列表', listings_url, class: 'btn btn-default'%>
    <% end %>
  </div>
</div>

app/views/listings/new_history.js.erb
$('#crawl_listing').innerText = '抓取新历史';
<% if @listing_history.errors.empty? %>
alert('成功添加一个时间在' + ' <%= @listing_history.created_at %> ' + '的历史')
<% else %>
alert('<%= @listing_history..errors.full_messages.join(', ') %>');
<% end %>

app/views/listings/prod_desc.html.erb
<div class="row">
  <div class="col-md-12">
    <h4>Listing: <%= @listing_history.listing.asin %> -- <%= @listing_history.created_at %></h4>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= @listing_history.prod_desc.html_safe %>
  </div>
</div>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>查看 Listing 信息</h1>
    <h4>ID: <%= @listing.id %></h4>
    <h4>Name: <%= @listing.name %></h4>
    <h4>ASIN: <%= @listing.asin %></h4>
    <h4>Tags:
      <% @listing.tags.each do |tag| %>
        <span class="label label-info"><%= tag.name %></span>
      <% end %>
    </h4>
  </div>
</div><br/>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to '修改', edit_listing_url(@listing), class: 'btn btn-primary' %>
    <%= link_to '返回列表', listings_url, class: 'btn btn-primary' %>
  </div>
</div>