config/routes.rb
Rails.application.routes.draw do
  root 'application#wellcome'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/listing_historys/:id/prod_desc', to: 'listings#prod_desc', via: 'get', :as => 'prod_desc'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :channels do
    member do
      get 'listings/new', to: 'listings#new'
    end
  end

  resources :listings do
    member do
      post '/historys', to: 'listings#new_history'
      get '/historys', to: 'listings#historys'
    end
  end
end

app/views/shared/_flash_alert.html.erb
<% [:info, :danger, :warning, :success].each do |type| %>
    <% if flash[type] %>
        <p class="alert text-center alert-<%= type %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= flash[type] %>
        </p>
    <% end %>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="controller-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#etracker_navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Brand', root_url, class: 'navbar-brand' %>
    </div>

    <div class="navbar-collapse collapse" id="etracker_navbar">
      <ul class="nav navbar-nav">
        <li class="<%= is_active?('channels') %>">
          <%= link_to '渠道列表', channels_url%>
        </li>
        <li class="<%= is_active?('listings') %>">
          <%= link_to 'Listing 列表', listings_url%>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if signed_in? %>
            <%= link_to '登出', signout_url, method: "delete"%>
          <% else %>
            <%= link_to '登陆', signin_url%>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_validate_errors.html.erb
<% if model.errors.any? %>
    <div class="col-md-12">
      <div id="error_explanation" class="bg-danger">
        <h2>Oops, 出现了<%= model.errors.count %>个错误</h2>

        <ul>
          <% model.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>